baseURL = "https://hugo-starter-site.netlify.app"
languageCode = "en-us"
title = "Nihal Sahu"
copyright = ""

rssLimit = 20
staticDir = "static"
canonifyURLs = true

[params]
	author.name = "Nihal Sahu"
	author.email = "iamnihalsahu@gmail.com"

[markup.goldmark.renderer]
    unsafe = "true"
