[[redirects]]
  from = "patience"
  to = "https://nihalsahu.substack.com/p/patience"

[[redirects]]
  from = "amis"
  to = "https://nihalsahu.substack.com/p/amis"

[[redirects]]
  from = "against-lawyer-brain"
  to = "https://nihalsahu.substack.com/p/against-lawyer-brain"

[[redirects]]
  from = "rks"
  to = "https://nihalsahu.substack.com/p/rks"

[[redirects]]
  from = "your-writing-is-not-good-enough"
  to = "https://nihalsahu.substack.com/p/your-writing-is-not-good-enough"

[[redirects]]
  from = "religious-freedom"
  to = "https://nihalsahu.substack.com/p/religious-freedom"

[[redirects]]
  from = "umesh"
  to = "https://nihalsahu.substack.com/p/umesh"

[[redirects]]
  from = "chief-justice"
  to = "https://nihalsahu.substack.com/p/chief-justice"

[[redirects]]
  from = "extremely-basic-productivity-advice/"
  to = "https://nihalsahu.substack.com/p/extremely-basic-productivity-advice"

[[redirects]]
  from = "the-levine-question"
  to = "https://nihalsahu.substack.com/p/the-levine-question"

[[redirects]]
  from = "tipping-the-odds"
  to = "https://nihalsahu.substack.com/p/tipping-the-odds"

[[redirects]]
  from = "regina"
  to = "https://nihalsahu.substack.com/p/regina"

[[redirects]]
  from = "government-health-spending"
  to = "https://nihalsahu.substack.com/p/government-health-spending"

