[[redirects]]
  from = "/patience"
  to = "https://nihalsahu.substack.com/p/patience"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/amis"
  to = "https://nihalsahu.substack.com/p/amis"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/against-lawyer-brain"
  to = "https://nihalsahu.substack.com/p/against-lawyer-brain"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/rks"
  to = "https://nihalsahu.substack.com/p/rks"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/your-writing-is-not-good-enough"
  to = "https://nihalsahu.substack.com/p/your-writing-is-not-good-enough"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/religious-freedom"
  to = "https://nihalsahu.substack.com/p/religious freedom"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/umesh"
  to = "https://nihalsahu.substack.com/p/umesh freedom"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/chief-justice"
  to = "https://nihalsahu.substack.com/p/chief-justice freedom"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/extremely-basic-productivity-advice/"
  to = "https://nihalsahu.substack.com/p/extremely-basic-productivity-advice"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/the-levine-question"
  to = "https://nihalsahu.substack.com/p/the-levine-question"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/tipping-the-odds"
  to = "https://nihalsahu.substack.com/p/tipping-the-odds"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/regina"
  to = "https://nihalsahu.substack.com/p/regina"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/government-health-spending"
  to = "https://nihalsahu.substack.com/p/government-health-spending"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

